### PR TITLE
Release v1.1.0

### PR DESCRIPTION
**Pull request by williambrandler**
## What changes are proposed in this pull request?
Release v1.0.0. There are now in [Maven Central](https://search.maven.org/search?q=g:io.projectglow) and [pypi](https://pypi.org/project/glow.py/).

## How is this patch tested?
- [ ] Unit tests
- [ ] Integration tests
- [ ] Manual tests

(Details)

### CODE REVIEW

**Comment by karenfeng** [comment]
Thanks for taking care of this @williambrandler! I see the Maven release here https://repo1.maven.org/maven2/io/projectglow/ but not in Central https://search.maven.org/search?q=g:io.projectglow; do you know what's going on?

**Comment by williambrandler** [comment]
@karenfeng it wasn't there when I made the PR 

(docs say it takes a few hours to show up so was banking on it being there by the time you read this!)

It is on maven central now
https://search.maven.org/search?q=glow

**Review by karenfeng — APPROVED** [review]
Nice! Thanks @williambrandler, it's synced faster in the past so I wasn't sure what was happening.
One nit: can you revise the commits with signoff and force push? (See https://github.com/projectglow/glow/pull/406/checks?check_run_id=3581220949 for more instructions.)
Otherwise, LGTM.

**Comment by williambrandler** [comment]
thanks @karenfeng I followed those instructions...

**Pull request closed without merging**
