### PR TITLE
Workaround for discordant GWAS results between Glow, Hail, and statsmodel

### PR DESCRIPTION
**Pull request by bcajes**
## What changes are proposed in this pull request?
Potential workaround for discordant gwas results between Glow gwas (with and without offsets), Hail, and statsmodel.  Hail gwas, for a single phenotype group , will intersect all non-null phenotypes, covariates, and genotypes and the results generated are concordant with statsmodel baselines when the same intersections are applied.  Glow regressions do not match hail and statsmodel results outside of unit tests for the same input, despite sample masks being applied under the hood.  Running glow gwas on real-world phenotype data with high missingness results in massive inflation/deflation of pvalues.  But, performing this intersection upstream of calling glow gwas, results in concordance with Hail and statsmodel.  One problem with applying this intersection in glow is that transformation on a glow genotype dataframe is not efficient.  This prototype integrates a new "intersect_samples" flag and a parameter to pass in the genotype_sample_ids and performs this intersection in numpy within the existing mapPandas call, without having to do a more expensive spark dataframe transformation upstream.

## How is this patch tested?
- [ x ] Unit tests
- [ ] Integration tests
- [ x ] Manual tests - ran linreg on real-world data with high missingness and confirmed concordance with hail and statsmodel

Inflation/deflation can also be observed in offset generation, though to a much lesser extent than is seen with gwas.  Applying a similar approach for the initial steps of WGR is more complicated.  I'll leave this as a draft for now in hopes there is a more elegant solution that can be applied to all steps of WGR, as well.  I'm also building off of my hail enhancement branch: https://github.com/projectglow/glow/pull/377

### CODE REVIEW

**Comment by williambrandler** [comment]
Hey @bcajes thanks for this!

I replicated the inflation of P values with 30% missingness and 10k simulated samples

qqplot

@henrydavidge what do you think?

**Comment by williambrandler** [comment]
Firth regression seems fine:

qqplot_firth

**Comment by henrydavidge** [comment]
@williambrandler can you share your code?

**Comment by williambrandler** [comment]
hey @henrydavidge it's a series of notebooks, 
published using databricks community edition,

[simulate covariates](https://databricks-prod-cloudfront.cloud.databricks.com/public/4027ec902e239c93eaaa8714f173bcfc/8320872975591174/3055309075932722/7059035168435387/latest.html)

[simulate pvcf](https://databricks-prod-cloudfront.cloud.databricks.com/public/4027ec902e239c93eaaa8714f173bcfc/8320872975591174/3055309075932699/7059035168435387/latest.html)

[linreg](https://databricks-prod-cloudfront.cloud.databricks.com/public/4027ec902e239c93eaaa8714f173bcfc/8320872975591174/3055309075932651/7059035168435387/latest.html)

[firth](https://databricks-prod-cloudfront.cloud.databricks.com/public/4027ec902e239c93eaaa8714f173bcfc/8320872975591174/3055309075932675/7059035168435387/latest.html)

[explore linreg](https://databricks-prod-cloudfront.cloud.databricks.com/public/4027ec902e239c93eaaa8714f173bcfc/8320872975591174/3055309075932743/7059035168435387/latest.html)

[explore firth](https://databricks-prod-cloudfront.cloud.databricks.com/public/4027ec902e239c93eaaa8714f173bcfc/8320872975591174/3055309075932752/7059035168435387/latest.html)

**Comment by williambrandler** [comment]
hey @henrydavidge I reran the analysis and updated the notebooks using just 100 samples and 1000 variants. 

You see the inflation for linear regression even at that level (and not in hail). So this scale of data can be used for unit testing

**Comment by williambrandler** [comment]
hey @bcajes to fix DCO, 

#download the gh cli
brew install gh
#authenticate to github using [authentication token](https://docs.github.com/en/github/authenticating-to-github/keeping-your-account-and-data-secure/creating-a-personal-access-token)

`gh pr checkout https://github.com/projectglow/glow/pull/391`
#rebase
`git rebase HEAD~58 --signoff`
#resolve any conflicts then force push
git push --force-with-lease origin sample_mask

**Comment by bcajes** [comment]
@williambrandler did a bit of cleanup and added doc strings around intersect_samples https://github.com/projectglow/glow/pull/391/commits/4ebc29807752f95fa4cc214c195026ae3f99d584. Finally got DCO to pass https://github.com/projectglow/glow/pull/391/checks, but the git rebase HEAD~58 --signoff operation makes the history quite ugly. There seems to be some sort of authorization error in the docs test. Everything else passes.

**Comment by williambrandler** [comment]
thanks @bcajes oh yeah now it is saying `+19,782 −3,588` changes, looks like it is including old commits that have already merged in. It happened to my PR also, I need to look into this

Also plan to look into the authorization issue for the notebook tests tomorrow

**Comment by bcajes** [comment]
DCO fix caused some messy git history.  Creating a new PR to clean it up.

**Pull request closed without merging**
