### PR TITLE
Create integration test script

### LINKED ISSUE #374: Automatically test demo notebooks
A number of the demo notebooks are out-of-date, contain hidden paths, or are otherwise unusable. We should automatically test them to make sure that the notebooks are usable.

### PR DESCRIPTION
**Pull request by karenfeng**
## What changes are proposed in this pull request?

Resolves #374.

Creates a script to automatically launch all Glow demo notebooks as Databricks job runs, by performing the following flow:

- Upload demo notebooks to the workspace
- Upload init scripts to DBFS
- Launch job runs, including:
  + Attaching init scripts
  + Installing libraries
- Check job run status every 60s 

This script will run nightly to ensure we don't encounter any unintended regressions.

Updates notebooks that are not up-to-date.
During testing, I noticed that Spark 3.1 introduces some binary incompatibilities; I updated the docs to reflect that our users should stay in 3.0.

## How is this patch tested?
- [ ] Unit tests
- [x] Integration tests
- [x] Manual tests

CircleCI run of the `notebook-tests` job: https://app.circleci.com/pipelines/github/projectglow/glow/2147/workflows/8bffcc8e-4adb-4888-884e-c93b456b939e/jobs/5436
Manual test: `python docs/dev/run-nb-test.py`

### CODE REVIEW

**Comment by williambrandler** [comment]
thanks Karen! question, " I noticed that Spark 3.1 introduces some binary incompatibilities; I updated the docs to reflect that our users should stay in 3.0.", Hail supports Spark3.1, are we going to hit compatibility issues? How much effort is it to make glow work with Spark3.1?

**Comment by williambrandler** [comment]
also the other thing that would be great is a how to guide so that users can contribute notebooks and have them automatically tested. I have a notebook I would like to contribute, which can be a starting point. Will sync with you offline to work on this

**Comment by karenfeng** [comment]
To make Glow work with Spark 3.1, I believe we only need to cut a new release with the new dependency; the amount of work should be fairly minor. The version of Hail that we work with is built on 3.0.

**Comment by williambrandler** [comment]
sounds good

**Review by kianfar77 — APPROVED** [review]
Thanks @karenfeng

**Pull request merged**
